[Setting]
current_theme          = catppuccin
inject_theme_js        = 1
replace_colors         = 1
inject_css             = 1
overwrite_assets       = 1
spotify_launch_flags   = 
check_spicetify_update = 1
always_enable_devtools = 0
spotify_path           = /home/airyy/.local/share/flatpak/app/com.spotify.Client/x86_64/stable/ccc22a6757ff4a33e8b111de412d742ed1675e7eda22c016f3a4b3d2d8175a84/files/extra/share/spotify
prefs_path             = /home/airyy/.config/spotify/prefs
color_scheme           = mocha

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

[AdditionalOptions]
extensions            = 
custom_apps           = marketplace
sidebar_config        = 1
home_config           = 1
experimental_features = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.2.59.514.g834e17d4
with    = 2.40.11
