return {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = {
        custom_highlights = {
            TelescopeNormal = { bg = "#181825" },
            TelescopeBorder = { bg = "#181825" },

            TelescopePromptNormal = { bg = "#313244" },
            TelescopePromptBorder = { bg = "#313244" },
            TelescopePromptTitle = { bg = "#cba6f7", fg = "#1e1e2e", bold = true },

            TelescopeResultsTitle = { fg = "#181825" },

            TelescopePreviewTitle = { bg = "#cba6f7", fg = "#1e1e2e", bold = true },

            CmpItemKindVariable = { bg = "#45475a", bold = true },
            CmpItemKindValue = { bg = "#45475a", bold = true },
            CmpItemKindUnit = { bg = "#45475a", bold = true },
            CmpItemKindTypeParameter = { bg = "#45475a", bold = true },
            CmpItemKindType = { bg = "#45475a", bold = true },
            CmpItemKindText = { bg = "#45475a", bold = true },
            CmpItemKindTabNine = { bg = "#45475a", bold = true },
            CmpItemKindSuperMaven = { bg = "#45475a", bold = true },
            CmpItemKindStructure = { bg = "#45475a", bold = true },
            CmpItemKindStruct = { bg = "#45475a", bold = true },
            CmpItemKindSnippet = { bg = "#45475a", bold = true },
            CmpItemKindReference = { bg = "#45475a", bold = true },
            CmpItemKindProperty = { bg = "#45475a", bold = true },
            CmpItemKindOperator = { bg = "#45475a", bold = true },
            CmpItemKindModule = { bg = "#45475a", bold = true },
            CmpItemKindMethod = { bg = "#45475a", bold = true },
            CmpItemKindKeyword = { bg = "#45475a", bold = true },
            CmpItemKindInterface = { bg = "#45475a", bold = true },
            CmpItemKindIdentifier = { bg = "#45475a", bold = true },
            CmpItemKindFunction = { bg = "#45475a", bold = true },
            CmpItemKindFolder = { bg = "#45475a", bold = true },
            CmpItemKindFile = { bg = "#45475a", bold = true },
            CmpItemKindField = { bg = "#45475a", bold = true },
            CmpItemKindEvent = { bg = "#45475a", bold = true },
            CmpItemKindEnumMember = { bg = "#45475a", bold = true },
            CmpItemKindEnum = { bg = "#45475a", bold = true },
            CmpItemKindCopilot = { bg = "#45475a", bold = true },
            CmpItemKindConstructor = { bg = "#45475a", bold = true },
            CmpItemKindConstant = { bg = "#45475a", bold = true },
            CmpItemKindColor = { bg = "#45475a", bold = true },
            CmpItemKindCodeium = { bg = "#45475a", bold = true },
            CmpItemKindClass = { bg = "#45475a", bold = true },
            CmpItemKindMatch = { bg = "#45475a", bold = true },
        },
    },
}
