format = '''
╭────>\($username@$hostname\) ─ $directory
│$git_branch$git_status$package$nodejs
╰─>
'''
scan_timeout = 10

add_newline = false

[directory]
style = "cyan"

[username]
show_always = true
style_user = "cyan"
format = '[$user]($style)'

[hostname]
format = '[$hostname]($style)'
style = "cyan"
ssh_only = false
disabled = false

[time]
disabled = false
format = '[$time]($style) '
time_format = '%T'
utc_time_offset = '-1'

[git_branch]
symbol = " "

[package]
symbol = " "